/**
 * Unix User Management Utilities
 *
 * Provides utilities for managing Unix users for Agor.
 * Users follow the naming convention: agor_<short-id> or custom unix_username.
 *
 * @see context/guides/rbac-and-unix-isolation.md
 */

import { execSync } from 'node:child_process';
import type { UnixUserMode } from '../config/types.js';
import { formatShortId } from '../lib/ids.js';
import type { UserID, UUID } from '../types/index.js';
import { escapeShellArg } from './run-as-user.js';
import { AGOR_USER_ADMIN } from './wrapper-constants.js';

// Re-export so call-sites can `import { AGOR_USER_ADMIN } from './user-manager.js'`
// during the transition. New code should import from './wrapper-constants.js' directly.
export { AGOR_USER_ADMIN };

/**
 * Default home directory base for Agor users
 */
export const AGOR_HOME_BASE = '/home';

/**
 * Default shell for new Agor users
 */
export const AGOR_DEFAULT_SHELL = '/bin/bash';

/**
 * Agor worktrees directory name within user home
 */
export const AGOR_WORKTREES_DIR = 'agor/worktrees';

/**
 * Generate a default Unix username for an Agor user
 *
 * Format: agor_<short-id>
 * Example: agor_03b62447
 *
 * @param userId - Full user UUID
 * @returns Unix username (e.g., 'agor_03b62447')
 */
export function generateUnixUsername(userId: UserID): string {
  const shortId = formatShortId(userId as UUID);
  return `agor_${shortId}`;
}

/**
 * Parse user short ID from Unix username
 *
 * @param username - Unix username (e.g., 'agor_03b62447')
 * @returns Short user ID (8 chars) or null if not an auto-generated name
 */
export function parseUnixUsername(username: string): string | null {
  const match = username.match(/^agor_([0-9a-f]{8})$/);
  return match ? match[1] : null;
}

/**
 * Check if username follows Agor auto-generated format
 *
 * @param username - Username to validate
 * @returns true if matches agor_<8-hex-chars> format
 */
export function isAutoGeneratedUsername(username: string): boolean {
  return /^agor_[0-9a-f]{8}$/.test(username);
}

/**
 * Validate Unix username format
 *
 * Unix usernames must:
 * - Start with lowercase letter or underscore
 * - Contain only lowercase letters, digits, underscores, hyphens
 * - Be 1-32 characters long
 *
 * @param username - Username to validate
 * @returns true if valid Unix username
 */
export function isValidUnixUsername(username: string): boolean {
  return /^[a-z_][a-z0-9_-]{0,31}$/.test(username);
}

/**
 * Validate that a username/password pair is safe to feed to chpasswd via stdin.
 *
 * chpasswd parses input as `username:password\n` records. Newlines in the
 * password would break into new records, and a colon in the username would be
 * interpreted as the username/password separator — both allowing an attacker
 * to change other users' passwords.
 *
 * @throws Error if username or password would corrupt chpasswd's parser.
 */
export function assertChpasswdInputSafe(username: string, password: string): void {
  if (typeof username !== 'string' || username.length === 0) {
    throw new Error('Refusing to sync password: unix_username is empty');
  }
  if (username.includes(':')) {
    throw new Error(
      'Refusing to sync password: unix_username contains ":" (chpasswd field separator)'
    );
  }
  if (/[\r\n\0]/.test(username)) {
    throw new Error('Refusing to sync password: unix_username contains newline or NUL byte');
  }
  if (typeof password !== 'string' || password.length === 0) {
    throw new Error('Refusing to sync password: password is empty');
  }
  // Mirror docker/sudoers/agor-user-admin's assert_safe_password so we fail
  // fast in Node rather than letting the wrapper reject with a less helpful
  // error. The two checks must stay in sync — relaxing one without the other
  // creates a silent gap.
  if (/[\r\n\0]/.test(password)) {
    throw new Error('Refusing to sync password: password contains newline or NUL byte');
  }
  if (password.includes(':')) {
    throw new Error('Refusing to sync password: password contains ":" (chpasswd field separator)');
  }
  if (Buffer.byteLength(password, 'utf8') > 256) {
    throw new Error('Refusing to sync password: password exceeds 256 bytes');
  }
  // Printable ASCII 0x20..0x7E only — matches wrapper's [[:print:]] check
  // under LC_ALL=C.
  if (/[^\x20-\x7e]/.test(password)) {
    throw new Error('Refusing to sync password: password contains non-printable bytes');
  }
}

/**
 * Get home directory path for a Unix user
 *
 * @param username - Unix username
 * @param homeBase - Base directory for homes (default: /home)
 * @returns Full home directory path
 */
export function getUserHomeDir(username: string, homeBase: string = AGOR_HOME_BASE): string {
  return `${homeBase}/${username}`;
}

/**
 * Get Agor worktrees directory path for a user
 *
 * @param username - Unix username
 * @param homeBase - Base directory for homes (default: /home)
 * @returns Full path to ~/agor/worktrees
 */
export function getUserWorktreesDir(username: string, homeBase: string = AGOR_HOME_BASE): string {
  return `${homeBase}/${username}/${AGOR_WORKTREES_DIR}`;
}

/**
 * Unix user management commands (to be executed via sudo).
 *
 * These are shell command strings. Every privileged operation routes through
 * the root-owned {@link AGOR_USER_ADMIN} wrapper, which validates verbs and
 * arguments before invoking the underlying tool. The sudoers file grants
 * NOPASSWD on that single wrapper path — not on useradd/usermod/gpasswd/
 * chpasswd/find directly. See docker/sudoers/agor-user-admin.
 */
export const UnixUserCommands = {
  /**
   * Check if a Unix user exists
   *
   * @param username - Unix username
   * @returns Command string (exits 0 if exists, non-zero if not)
   */
  userExists: (username: string) => `id "${username}" > /dev/null 2>&1`,

  /**
   * Create a new Unix user with home directory.
   *
   * Fixed shape: `useradd -m [-d <home>] -s /bin/bash -- <user>`.
   *
   * The wrapper's `--home` flag preserves UnixIntegrationService's
   * `homeBase` configurability without giving useradd a wildcard `-d`:
   * the wrapper validates that the supplied home dir matches exactly
   * `/home/<user>` or `/var/agor/<user>` (no traversal, no extra path
   * components). When `homeDir` is omitted, useradd falls back to the
   * system default HOME base (typically `/home`).
   *
   * @param username - Unix username to create
   * @param homeDir - Optional explicit home directory. Must equal
   *                  `${homeBase}/${username}` for the wrapper to accept it.
   * @returns Command string
   */
  createUser: (username: string, homeDir?: string) => {
    const homePart = homeDir ? `--home ${escapeShellArg(homeDir)} ` : '';
    return `sudo -n ${AGOR_USER_ADMIN} add-user ${homePart}${escapeShellArg(username)}`;
  },

  /**
   * Delete a Unix user (keeps home directory)
   *
   * @param username - Unix username to delete
   * @returns Command string
   */
  deleteUser: (username: string) =>
    `sudo -n ${AGOR_USER_ADMIN} delete-user ${escapeShellArg(username)}`,

  /**
   * Get command array for setting a Unix user's password via the wrapper.
   *
   * SECURITY: Used with execWithInput(). The password MUST be passed via
   * stdin (not argv) to avoid:
   *  1. Command injection (shell metacharacters in password)
   *  2. Exposure in process listings (ps aux)
   *  3. Exposure in shell history
   *
   * The wrapper reads the password from stdin (no newline required), runs
   * `chpasswd` internally as `<username>:<password>`, and only supports
   * usernames that pass its own validator.
   *
   * @param username - Unix username whose password to set
   * @returns Command array for execWithInput
   *
   * @example
   * ```ts
   * const cmd = UnixUserCommands.setPasswordCommand(user.unix_username);
   * const input = UnixUserCommands.formatPasswordInput(user.unix_username, password);
   * await executor.execWithInput(cmd, { input });
   * ```
   */
  setPasswordCommand: (username: string): string[] => [
    'sudo',
    '-n',
    AGOR_USER_ADMIN,
    'set-password',
    username,
  ],

  /**
   * Format stdin input for the set-password verb.
   *
   * Validates inputs via {@link assertChpasswdInputSafe} for defense-in-depth;
   * the wrapper re-validates too.
   *
   * @param username - Unix username
   * @param password - Plaintext password to set
   * @returns The raw password (no username prefix, no trailing newline).
   *          The wrapper composes the `user:password` record internally.
   * @throws Error if username or password contain chpasswd-unsafe characters
   */
  formatPasswordInput: (username: string, password: string): string => {
    assertChpasswdInputSafe(username, password);
    return password;
  },

  /**
   * Delete a Unix user and their home directory
   *
   * @param username - Unix username to delete
   * @returns Command string
   */
  deleteUserWithHome: (username: string) =>
    `sudo -n ${AGOR_USER_ADMIN} delete-user --remove-home ${escapeShellArg(username)}`,

  /**
   * Lock a Unix user account (disable login)
   *
   * @param username - Unix username
   * @returns Command string
   */
  lockUser: (username: string) =>
    `sudo -n ${AGOR_USER_ADMIN} lock-user ${escapeShellArg(username)}`,

  /**
   * Unlock a Unix user account
   *
   * @param username - Unix username
   * @returns Command string
   */
  unlockUser: (username: string) =>
    `sudo -n ${AGOR_USER_ADMIN} unlock-user ${escapeShellArg(username)}`,

  /**
   * Get user's UID
   *
   * @param username - Unix username
   * @returns Command string (outputs UID)
   */
  getUserUid: (username: string) => `id -u "${username}"`,

  /**
   * Get user's primary GID
   *
   * @param username - Unix username
   * @returns Command string (outputs GID)
   */
  getUserGid: (username: string) => `id -g "${username}"`,

  /**
   * Get all groups a user belongs to
   *
   * @param username - Unix username
   * @returns Command string (outputs space-separated group names)
   */
  getUserGroups: (username: string) => `id -nG "${username}"`,

  /**
   * Create directory with proper ownership
   *
   * Returns an array of commands to be executed sequentially.
   * Commands include sudo -n and can be run directly.
   *
   * @param path - Directory path to create
   * @param username - Owner username
   * @param group - Owner group (defaults to username)
   * @param mode - Permission mode (default: 755)
   * @returns Array of command strings to execute sequentially
   */
  createOwnedDirectory: (
    path: string,
    username: string,
    group?: string,
    mode: string = '755'
  ): string[] => {
    const grp = group || username;
    return [
      `sudo -n mkdir -p "${path}"`,
      `sudo -n chown "${username}:${grp}" "${path}"`,
      `sudo -n chmod ${mode} "${path}"`,
    ];
  },

  /**
   * Setup Agor worktrees directory structure for a user
   *
   * Creates ~/agor/worktrees with proper ownership.
   * Returns an array of commands to be executed sequentially.
   *
   * @param username - Unix username
   * @param homeBase - Home directory base
   * @returns Array of command strings to execute sequentially
   */
  setupWorktreesDir: (username: string, homeBase: string = AGOR_HOME_BASE): string[] => {
    const worktreesDir = `${homeBase}/${username}/${AGOR_WORKTREES_DIR}`;
    return [
      `sudo -n mkdir -p "${worktreesDir}"`,
      `sudo -n chown -R "${username}:${username}" "${homeBase}/${username}/agor"`,
    ];
  },
} as const;

/**
 * Error thrown when attempting to impersonate a non-existent Unix user
 */
export class UnixUserNotFoundError extends Error {
  constructor(
    public readonly username: string,
    message?: string
  ) {
    super(message ?? `Unix user "${username}" does not exist on this system`);
    this.name = 'UnixUserNotFoundError';
  }
}

/**
 * Check if a Unix user exists on the system
 *
 * @param username - Unix username to check
 * @returns true if user exists
 */
export function unixUserExists(username: string): boolean {
  try {
    execSync(`id "${username}" > /dev/null 2>&1`, { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Re-export of {@link UnixUserMode} for existing `@agor/core/unix` consumers.
 * Canonical definition lives in `@agor/core/config/types` so browser-safe
 * surfaces (e.g. `@agor/core/client`) can use it without pulling in this
 * Node-only module.
 */
export type { UnixUserMode };

/**
 * Result of resolving which Unix user to impersonate
 */
export interface ImpersonationResult {
  /** Unix username to impersonate, or null for no impersonation */
  unixUser: string | null;
  /** Human-readable reason for the decision */
  reason: string;
}

/**
 * Options for resolving Unix user impersonation
 */
export interface ResolveImpersonationOptions {
  /** Unix user mode from config */
  mode: UnixUserMode;
  /** User's unix_username (from authenticated user or session creator) */
  userUnixUsername?: string | null;
  /** Fallback executor user from config */
  executorUnixUser?: string | null;
}

/**
 * Resolve which Unix user to impersonate based on mode and available users
 *
 * This is the central logic for determining impersonation across:
 * - Terminal sessions (uses authenticated user's unix_username)
 * - Executor spawning (uses session's unix_username)
 *
 * @param options - Resolution options
 * @returns ImpersonationResult with user and reason
 * @throws Error if strict mode and no unix_username provided
 *
 * @example
 * ```ts
 * const result = resolveUnixUserForImpersonation({
 *   mode: 'strict',
 *   userUnixUsername: 'alice',
 * });
 * // result.unixUser = 'alice' (throws if alice doesn't exist)
 * ```
 */
export function resolveUnixUserForImpersonation(
  options: ResolveImpersonationOptions
): ImpersonationResult {
  const { mode, userUnixUsername, executorUnixUser } = options;

  switch (mode) {
    case 'simple':
      // No impersonation - run as current user
      return {
        unixUser: null,
        reason: 'simple mode - no impersonation',
      };

    case 'insulated':
      // Always use executor user from config
      return {
        unixUser: executorUnixUser ?? null,
        reason: executorUnixUser
          ? `insulated mode - using executor: ${executorUnixUser}`
          : 'insulated mode - no executor configured',
      };

    case 'strict':
      // Require user's unix_username, fail if not set
      if (!userUnixUsername) {
        throw new Error(
          'Strict Unix user mode requires unix_username to be set. ' +
            'Ensure the user has a unix_username configured.'
        );
      }
      return {
        unixUser: userUnixUsername,
        reason: `strict mode - using unix_username: ${userUnixUsername}`,
      };

    default:
      console.warn(`⚠️ Unknown unix_user_mode: ${mode}, falling back to simple mode`);
      return {
        unixUser: null,
        reason: 'unknown mode - defaulting to no impersonation',
      };
  }
}

/**
 * Validate that a resolved Unix user exists (for strict/insulated modes)
 *
 * Call this after resolveUnixUserForImpersonation for modes that require validation.
 *
 * @param mode - Unix user mode
 * @param unixUser - Resolved Unix user (from resolveUnixUserForImpersonation)
 * @throws Error with user-friendly message if user doesn't exist
 */
export function validateResolvedUnixUser(mode: UnixUserMode, unixUser: string | null): void {
  // Only validate for strict/insulated modes
  if ((mode === 'strict' || mode === 'insulated') && unixUser) {
    if (!unixUserExists(unixUser)) {
      throw new UnixUserNotFoundError(
        unixUser,
        `${mode === 'strict' ? 'Strict' : 'Insulated'} Unix user mode: ` +
          `user "${unixUser}" does not exist on this system. ` +
          'Ensure the Unix user is created first.'
      );
    }
  }
}
