export default {
  index: 'Overview',
  'getting-started': 'Getting Started',
  concepts: 'Concepts',
  assistants: 'Assistants',
  '--- Features': {
    type: 'separator',
    title: 'Features',
  },
  'internal-mcp': 'Agor MCP Server',
  'environment-configuration': 'Environments',
  scheduler: 'Scheduler',
  'spawned-subsessions': 'Spawned Subsessions',
  'message-gateway': 'Message Gateway (Beta)',
  'advanced-features': 'Advanced Features',
  cards: 'Cards (Beta)',
  artifacts: 'Artifacts (Beta)',
  architecture: 'Architecture',
  'sdk-comparison': 'SDK Comparison',
  '--- Development': {
    type: 'separator',
    title: 'Development',
  },
  development: 'Development Guide',
  '--- Deployment': {
    type: 'separator',
    title: 'Deployment',
  },
  'multiplayer-unix-isolation': 'Full Multiplayer Mode',
  'containerized-execution': 'Containerized Execution',
};
